dvsa/.github

CONTRIBUTING.md
- Adapted from Lambda Starter project
=> Add new contributing guide

pull_request_template.md
- Followed Lambda Starter and MOT History templates
- Ticket [RSP-1996](https://dvsa.atlassian.net/browse/RSP-1996)
=> feat: New PR template

.github/actions/install-deps/action.yaml, .github/workflows/nodejs-build.yaml, .github/workflows/nodejs-lint.yaml, .github/workflows/nodejs-security.yaml, .github/workflows/nodejs-test.yaml, README.md
- Taken from recent serverless repos
- Should pass in all configurable options to make workflows generic enough for different projects to use
- Workflows for linting, testing, building and security. Other workflows to follow
- 
- [x Did you make sure to update any documentation relating to this change?
=> feat: New GitHub actions

README.md, workflow-templates/ci.properties.json, workflow-templates/ci.yaml, workflow-templates/snyk-monitor.properties.json, workflow-templates/snyk-monitor.yaml
- Allows projects to easily pull in workflows
- Updated README documentation
- Workflow for generic ci workflow and synk monitoring
=> feat: New workflow starter templates

README.md, workflow-templates/ci.properties.json, workflow-templates/ci.yaml
- Broken indentation in workflow fixed
- Missing part of path in workflow fixed
- Updated documentation
Related issue:n/a
=> feat: Add extra info to README and fix indentation

README.md
- add note on snyk scanning default settings.
=> Docs: tweaking README formatting for readability

.github/workflows/nodejs-publish.yaml, README.md, workflow-templates/npm-publish.properties.json, workflow-templates/npm-publish.yaml
- Created nodejs-publish.yaml workflow
- Added Publish workflow template
- Updated Starter Workflow section to include notes about publishing to NPMJS and required secrets
- Added section to describe the new npm-publish.yaml workflow
Related issue: [RSP-2060](https://dvsa.atlassian.net/jira/software/c/projects/RSP/boards/830?modal=detail&selectedIssue=RSP-2060)
=> feat: create npmjs publish workflow

.github/workflows/update-lambda-function.yaml, README.md, workflow-templates/ci.yaml
- Workflow takes bucket name and object and updates the lambda to use this code
- Requires permission in terraform to enable GitHub to update function
Related issue: [RSP-2079](https://dvsa.atlassian.net/browse/RSP-2079)
=> feat: New workflow to Update Lambda Code on AWS

.github/workflows/update-lambda-function.yaml
- Add query filter to response from AWS CLI when the code is updated to prevent unnecessary details getting logged out
=> fix: Stop outputting Lambda Update Code output

workflow-templates/ci.yaml
Update workflow template to use latest version and fix inputs 
=> fix: fix workflow template

.github/workflows/java-test.yaml
Added a working directory for instances when the pom is not in the root of the project
=> amended to include working directory

.github/workflows/php-library-security.yml, .github/workflows/php-library-static.yml, .github/workflows/php-library-tests.yml, .github/workflows/php-security.yml, .github/workflows/php-static.yml, .github/workflows/php-tests.yml, workflow-templates/php-library-security.properties.json, workflow-templates/php-library-security.yml, workflow-templates/php-library-static.properties.json, workflow-templates/php-library-static.yml, workflow-templates/php-library-tests.properties.json, workflow-templates/php-library-tests.yml, workflow-templates/php-security.properties.json, workflow-templates/php-security.yml, workflow-templates/php-static.properties.json, workflow-templates/php-static.yml, workflow-templates/php-tests.properties.json, workflow-templates/php-tests.yml
Adding in PHP library workflows 
=> feat: php library workflows

README.md, workflow-templates/php-library-security.yml, workflow-templates/php-library-static.yml, workflow-templates/php-library-tests.yml
=> Release 3.2.2

.github/workflows/php-library-security.yml
Fix issues with permissions and variable typo on security workflow
Related issue: N/A
=> Fix library security permissions

README.md
=> Amended readme version and library docs

.github/workflows/php-library-security.yml, .github/workflows/php-library-static.yml, .github/workflows/php-library-tests.yml, .github/workflows/php-tests.yml, README.md
Update matrix actions to add 'fail-fast' input. This will allow all of the matrix actions to finish even if one of them failed. 
Related issue: N/A
=> feat: Update matrix actions to add 'fail-fast' input

.github/actions/aws-auth/action.yml, .github/actions/aws-cli/action.yml, .github/actions/install-deps/action.yaml, .github/actions/java-config/action.yaml, .github/actions/terraform-action/action.yml, .github/actions/terraform-workspace/action.yml, .github/actions/update-pr/action.yml, .github/workflows/java-security.yaml, .github/workflows/java-snyk-update.yaml, .github/workflows/java-test.yaml, .github/workflows/nodejs-build.yaml, .github/workflows/nodejs-lint.yaml, .github/workflows/nodejs-publish.yaml, .github/workflows/nodejs-security.yaml, .github/workflows/nodejs-test.yaml, .github/workflows/php-library-security.yml, .github/workflows/php-library-static.yml, .github/workflows/php-library-tests.yml, .github/workflows/php-security.yml, .github/workflows/php-static.yml, .github/workflows/php-tests.yml, .github/workflows/update-lambda-function.yaml, .github/workflows/upload-to-s3.yaml, workflow-templates/check-pr-title.yaml, workflow-templates/ci.yaml, workflow-templates/snyk-monitor.yaml
Related issue: [BL-16691](https://dvsa.atlassian.net/browse/BL-16691)
=> feat!: update actions to node 20

.github/actions/aws-auth/README.md, .github/actions/aws-cli/README.md, .github/actions/java-config/README.md, .github/actions/terraform-action/README.md, .github/actions/terraform-workspace/README.md, .github/actions/update-pr/README.md, .github/workflows/nodejs-build.yaml, .github/workflows/nodejs-lint.yaml, .github/workflows/nodejs-publish.yaml, .github/workflows/nodejs-test.yaml, README.md, workflow-templates/ci.yaml, workflow-templates/npm-publish.yaml, workflow-templates/php-library-security.yml, workflow-templates/php-library-static.yml, workflow-templates/php-library-tests.yml, workflow-templates/php-security.yml, workflow-templates/php-static.yml, workflow-templates/php-tests.yml
Related issue: [BL-16691](https://dvsa.atlassian.net/browse/BL-16691)
=> feat: update readme to use release v4.0.0

.github/actions/aws-auth/README.md, .github/actions/aws-cli/README.md, .github/actions/java-config/README.md, .github/actions/terraform-action/README.md, .github/actions/terraform-workspace/README.md, .github/actions/update-pr/README.md, .github/workflows/nodejs-build.yaml, .github/workflows/nodejs-lint.yaml, .github/workflows/nodejs-test.yaml, README.md, workflow-templates/ci.yaml, workflow-templates/npm-publish.yaml, workflow-templates/php-library-security.yml, workflow-templates/php-library-static.yml, workflow-templates/php-library-tests.yml, workflow-templates/php-security.yml, workflow-templates/php-static.yml, workflow-templates/php-tests.yml
Related issue: [BL-16691](https://dvsa.atlassian.net/browse/BL-16691)
=> docs: update readme to use release v4.0.1

.github/actions/aws-auth/README.md, .github/actions/aws-cli/README.md, .github/actions/aws-waf-access/README.md, .github/actions/gatling-job-summary/README.md, .github/actions/gatling-job-summary/action.yml, .github/actions/java-config/README.md, .github/actions/terraform-action/README.md, .github/actions/terraform-action/action.yml, .github/actions/terraform-fmt/README.md, .github/actions/terraform-fmt/action.yml, .github/actions/terraform-workspace/README.md, .github/actions/terraform-workspace/action.yml, .github/actions/update-pr/README.md, .github/actions/update-pr/action.yml, .github/workflows/nodejs-build.yaml, .github/workflows/nodejs-lint.yaml, .github/workflows/nodejs-test.yaml, README.md, workflow-templates/ci.yaml, workflow-templates/npm-publish.yaml, workflow-templates/php-library-security.yml, workflow-templates/php-library-static.yml, workflow-templates/php-library-tests.yml, workflow-templates/php-security.yml, workflow-templates/php-static.yml, workflow-templates/php-tests.yml
Related issue: [BL-16691](https://dvsa.atlassian.net/browse/BL-16691)
=> fix: bump setup-terraform to v3

.github/actions/terraform-action/README.md, .github/actions/terraform-action/action.yml
Include optional input to set working directory of terraform code, will default to current working directory
Successful run with directory set to ./infrastructure
Expected failure if directory set incorrectly
=> feat: Set working directory of terraform code option

.github/workflows/terraform-static.yaml, README.md
Adds Terraform static workflow as well as detail in the readme.
=> feat: add terraform static

.github/workflows/terraform-static-full.yaml
Adds in a few fixes and corrections to existing workflows and scheduling.
=> fix: add additional workflow trigger and correct typo in run command

README.md
=> release bump

.github/workflows/terraform-static-full.yaml
=> fix: error in step sequencing for tfformat

.github/workflows/nodejs-build.yaml
fix a version issue
fix a version issue
=> fix: Update nodejs-build.yaml

.github/workflows/nodejs-lint.yaml, .github/workflows/nodejs-test.yaml, README.md
Update actions - routine maintenance
=> fix: add new versions to work flows

.github/workflows/php-security.yml, .github/workflows/php-static.yml, .github/workflows/php-tests.yml
added optional working_directory inputs to security, static and tests.
=> feat: added optional working directory

.github/workflows/php-library-static.yml, README.md
Have tested this works by using the PR below and pointing at this branch. Also tested the default behaviour works, to ensure existing functionality elsewhere is unaffected.
https://github.com/dvsa/olcs-xmltools/pull/17
Related issue: [VOL-6497](https://dvsa.atlassian.net/browse/VOL-6497)
[VOL-6497]: https://dvsa.atlassian.net/browse/VOL-6497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add option to change composer package stability levels VOL-6497
